name: manage-azure-policy-163a9bf6
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/All_resources_-_Audit_diagnostic_settings_event_hub_bb2d4e63-f450-48c6-b56d-831739d54ab2/**'
#      - .github/workflows/manage-azure-policy-163a9bf6.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_163a9bf6}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/All_resources_-_Audit_diagnostic_settings_event_hub_bb2d4e63-f450-48c6-b56d-831739d54ab2/**
